### ISSUE TITLE
Нужно исправить + можно лучше

### ISSUE THREAD

**Issue by uyriq** [uyriq/stellar-burger#22]
### типизация
- [x] типизация обычных функций не требуется. propTypes нужны для компонентов реакта 
- [x] в BurgerIngredientsItem неправильная типизация. Там приходит ingredient. Вот его нужно типизировать
- [x] Всем элементам props, которые являются обязательными, нужно добавлять isRequired при типизации с propTypes. Это касается самих массивов и объектов. В самом конце нужно указывать isRequired, если массив сам обязателен в props
### форматирование и codestyle
- [x] В чек-листе есть пункт: Начальное состояние стейт-переменных содержит корректный тип данных. #26
- [x] нужно отформатировать код, чтобы были видны нормальные отступы и вложенность одних компонентов в другие.
- [x] пустую clean up-функцию не нужно
- [ ] переменные в проекте нужно называть в camelCase
### Исправить ошибки
- [x] https://github.com/uyriq/stellar-burger/issues/24
### Refactors
- [ ] ограничивать кол-во срабатываний фильтраций массивов при помощи хука useMemo.
- [x] #27 не делать в каждом ингредиенте по модальному окну. Нужно было сделать одно окно для деталей в BurgerIngredients (или App) и передавать в каждый ингредиент функцию клика, в которой бы назначались данные для показа в окне 
- [x] #23 
- [x] #25

**Comment by uyriq** [comment]
осталось на будущее 

- [ ] - ограничивать кол-во срабатываний фильтраций массивов при помощи хука useMemo.
- [ ] - переменные в проекте нужно называть в camelCase
